### ISSUE TITLE
Documentation Issue

### ISSUE THREAD

**Issue by maykish** [Cranch-fur/Cursed-Market-Reborn#2]
I can implement the code in Epic but not Steam due to SSL error, and step 2 in the README file says to specify a file path in the program settings but I am confused about how to get to program settings. Also, I noticed that on some characters their perks are always set by default and I would like to know how I can change it so the perks I normally use are set for the characters I like to use by default. Not sure if there is a savefile or how I would use it? Side note: I'm a russian but my keyboard has english keyboard stickers only :(

If you need any help with this program I am a software engineer and would love to help with anything in my free time ✌😎

**Comment by Cranch-fur** [comment]
Better to text me in Discord, not on website i almost never visit Cranch#1678
