### ISSUE TITLE
Invalid JSON

### ISSUE THREAD

**Issue by 17241** [Cranch-fur/Cursed-Market-Reborn#5]
when i start cursed market, i see the message: Cursed market Filed to parse server Response!
Reason: Invalid JSON. 
How can i fix it? help me please
![изображение_2022-06-22_133213518](https://user-images.githubusercontent.com/107995799/175008378-1ef303ac-e116-4fc5-b88f-487389bb3564.png)

**Comment by Cranch-fur** [comment]
Cursed market server experience technical issues right now

ср, 22 июн. 2022 г., 13:33 17241 ***@***.***>:

**Comment by 17241** [comment]
ok. Will wait for ending of issues. Thanks for quick responce
